### ISSUE TITLE
Get Time from RealTimeClock

### ISSUE THREAD

**Issue by OSbOoL** [esoadamo/JavaUniPiControl#1]
Hi, can you show me how I can get the Time of the RealTimeClock? I don't know how to do it with this code.
It is possible to get the time with Class UniWatchTimerTask? If it's possible, what do I have to do?

Is there an easier way to get the Time without coding? Eventually settings in Linux system?

Thank you for this beautiful work, I love it an my Unipis work fine.

**Comment by esoadamo** [comment]
Hi, I greatly appreciate, that you enjoy using one of my projects :blush:
Unfortunately, it has been a long time that I have last used it myself and `UniWatchTimerTask` cannot do this, it is merely a subclass of classic Java `TimerTask`.
I can only suggest you to take a look at [UniPi's API](https://evok-14.api-docs.io/1.11/) and go from there.
If you will be able resolve this issue and would be keen on making a pull request, I will be happy to merge it!
